// svelte-pokedex/src/components/Pokedex/Pokedex.svelte
<script lang="ts">
import { Icon, Home, ArrowSmLeft, type IconSource } from 'svelte-hero-icons'
export let homeIcon: IconSource = Home
export let arrowIcon: IconSource = ArrowSmLeft

import DPad from '@components/DPad'
import Button from '@components/Button'
import BlueIndicator from './Indicators/BlueIndicator.svelte'
import SmallerIndicator from './Indicators/SmallerIndicator.svelte'
</script>

<div
  class="{`bg-gradient-to-br  from-pokedex-dark-red via-red-700 to-pokedex-dark-red border border-black h-full rounded-3xl ${$$props.class}`}">
  <!-- Wrapper -->
  <div class="grid grid-rows-6 h-full p-5">
    <!-- Indicator container  -->
    <div class="flex gap-4">
      <BlueIndicator />
      <SmallerIndicator intent="{'red'}" />
      <SmallerIndicator intent="{'yellow'}" />
      <SmallerIndicator intent="{'green'}" />
    </div>

    <!-- <Display class="mb-8 row-span-3">{children}</Display> -->

    <!-- Button container -->
    <div class="grid grid-cols-2 items-center mt-8 ml-8 md:ml-16">
      <div class="flex items-center gap-4">
        <Button intent="rounded" bgColor="grey" size="md">
          <Icon src="{homeIcon}" class="h-8 w-8" />
        </Button>

        <Button bgColor="blue" size="sm" intent="squared">
          <Icon src="{arrowIcon}" class="h-6 w-6" />
        </Button>
      </div>

      <DPad class="justify-self-end mr-8 md:mr-16" />
    </div>

    <!-- <SearchForm onSearch={onSearch} class="mx-8 md:mx-16" /> -->
  </div>
</div>

// react-pokedex/src/components/Pokedex/Pokedex.tsx
import { HomeIcon, ArrowUturnLeftIcon } from '@heroicons/react/24/outline'
import Button from '../Button'
import DPad from '../DPad'
import SearchForm from '../SearchForm'
import Display from './Display'
import BlueIndicator from './Indicators/BlueIndicator'
import SmallerIndicator from './Indicators/SmallerIndicator'
import { PokedexProps } from './Pokedex.types'

const Pokedex = ({ className, onSearch }: PokedexProps) => {
  return (
    <div
      className={`bg-gradient-to-br  from-pokedex-dark-red via-red-700 to-pokedex-dark-red border border-black h-full rounded-3xl ${className}`}
    >
      {/* Wrapper */}
      <div className="grid grid-rows-6 h-full p-5">
        {/* Indicator container */}
        <div className="flex gap-4 mb-2">
          <BlueIndicator />
          <SmallerIndicator intent={'red'} />
          <SmallerIndicator intent={'yellow'} />
          <SmallerIndicator intent={'green'} />
        </div>

        <Display className="mb-8 row-span-3" />

        {/* Button container */}
        <div className="grid grid-cols-2 items-center mt-8">
          <div className="flex items-center gap-4">
            <Button intent="rounded" bgColor="grey" size="md">
              <HomeIcon className="h-8 w-8" />
            </Button>

            <Button bgColor="blue">
              <ArrowUturnLeftIcon className="h-6 w-6" />
            </Button>
          </div>

          <DPad className="justify-self-end" />
        </div>

        <SearchForm onSearch={onSearch} />
      </div>
    </div>
  )
}

export default Pokedex
