// react-pokedex/src/App.tsx
import { useMemo } from 'react'
import {
  createSearchParams,
  Route,
  Routes,
  useNavigate,
  useSearchParams
} from 'react-router-dom'
import Fuse from 'fuse.js'
import Pokedex from '@components/Pokedex'
import { useGetAllPokemon } from '@hooks/useGetAllPokemon'
import HomePage from '@pages/HomePage'
import PokemonPage from '@pages/PokemonPage'
import SearchPage from '@pages/SearchPage'

function App() {
  const [searchParams] = useSearchParams()
  const query = searchParams.get('query')

  const { data: allPokemon } = useGetAllPokemon()
  const navigate = useNavigate()

  // Options for Fuse.js search
  const searchOptions = {
    threshold: 0.5,
    includeScore: true,
    keys: ['name']
  }

  // Initializing search func
  const fuse = allPokemon ? new Fuse(allPokemon, searchOptions) : undefined

  // Callback func for search
  function onSearch(query: string) {
    navigate({
      pathname: '/search',
      search: `?${createSearchParams({
        query: query
      })}`
    })
  }

  // Keeps searched results on re-render
  const searchResults = useMemo(() => {
    if (query) {
      // if query exists, results will return hits
      const result = fuse?.search(query).map((item) => item.item)
      return result
    }
  }, [query, allPokemon])

  return (
    <div className="h-full md:max-w-3xl md:m-auto md:py-8">
      <Pokedex onSearch={onSearch}>
        <Routes>
          <Route path="/" element={<HomePage data={allPokemon} />} />
          <Route path="/pokemon/:id" element={<PokemonPage />} />
          <Route path="/search" element={<SearchPage data={searchResults} />} />
        </Routes>
      </Pokedex>
    </div>
  )
}

export default App

// svelte-pokedex/src/App.svelte
<script lang="ts">
import { Router, Route, navigate } from 'svelte-navigator'
import Fuse from 'fuse.js'
import Pokedex from '@components/Pokedex'
import HomePage from '@pages/HomePage.svelte'
import PokemonPage from '@pages/PokemonPage.svelte'
import SearchPage from '@pages/SearchPage.svelte'
import { createQuery } from '@tanstack/svelte-query'
import { getAllPokemon } from '@services/PokemonAPI'

const query = createQuery<IPokemon[]>({
  queryKey: ['pokemons'],
  queryFn: () => getAllPokemon()
})

// Reacting to changes and setting data to variable
$: allPokemon = $query.data

// Options for Fuse.js search
const searchOptions = {
  threshold: 0.5,
  includeScore: true,
  keys: ['name']
}

const url = new URL(window.location.href)
let searchResults: IPokemon[]

// Initializing search func
$: fuse = allPokemon ? new Fuse(allPokemon, searchOptions) : undefined

function handleMessage(e) {
  navigate('/search')
  url.pathname = '/search'
  searchResults = fuse?.search(e.detail.query).map((item) => item.item)
  url.searchParams.set('query', e.detail.query)
  window.history.replaceState(null, '', url)
}
</script>

<div class="h-full md:max-w-3xl md:m-auto md:py-8">
  <Router>
    <Pokedex on:search="{handleMessage}">
      <Route path="/" primary="{false}">
        <HomePage data="{allPokemon}" />
      </Route>

      <Route path="/pokemon/:id" primary="{false}">
        <PokemonPage />
      </Route>

      <Route path="/search" primary="{false}">
        <SearchPage query="{searchResults}" />
      </Route>
    </Pokedex>
  </Router>
</div>
