// react-pokedex/src/components/DPad/DPad.tsx
import { DPadProps } from './DPad.types'

const DPad = ({ className }: DPadProps) => {
  return (
    <div className={`relative w-8 h-8 ${className}`}>
      <div className="bg-black w-8 h-8 border border-stone-800 absolute top-0 right-8"></div>
      <div className="bg-black w-8 h-8 border border-stone-800 absolute top-0 right-16"></div>
      <div className="bg-black w-8 h-8 border border-stone-800 absolute -top-8 right-8"></div>
      <div className="bg-black w-8 h-8 border border-stone-800 absolute top-0 left-0"></div>
      <div className="bg-black w-8 h-8 border border-stone-800 absolute top-8 right-8"></div>
    </div>
  )
}

export default DPad

// svelte-pokedex/src/components/DPad/DPad.svelte
<script lang="ts">
</script>

<div class="{`relative w-8 h-8 ${$$props.class}`}">
  <div class="bg-black w-8 h-8 border border-stone-800 absolute top-0 right-8">
  </div>
  <div class="bg-black w-8 h-8 border border-stone-800 absolute top-0 right-16">
  </div>
  <div class="bg-black w-8 h-8 border border-stone-800 absolute -top-8 right-8">
  </div>
  <div class="bg-black w-8 h-8 border border-stone-800 absolute top-0 left-0">
  </div>
  <div class="bg-black w-8 h-8 border border-stone-800 absolute top-8 right-8">
  </div>
</div>
