// solid-pokedex/src/App.tsx
import type { Component } from 'solid-js'
import { useGetAllPokemon } from '@hooks/useGetAllPokemon'

const App: Component = () => {
  const { data } = useGetAllPokemon()

  console.log('data', data)

  return (
    <div>
      <h1 class="text-3xl font-bold underline">Hello world!</h1>
    </div>
  )
}

export default App

// react-pokedex/src/App.tsx
import Pokedex from './components/Pokedex/Pokedex'
import { useGetAllPokemon } from './hooks/useGetAllPokemon'
import { useGetPokemon } from './hooks/useGetPokemon'

function App() {
  // const { data: pokemon } = useGetPokemon('mew')

  // console.log('pokemon', pokemon)

  // const { data: allPokemon } = useGetAllPokemon()

  // console.log('allPokemon', allPokemon)

  return (
    <div className="h-full">
      <Pokedex />
    </div>
  )
}

export default App
