// svelte-pokedex/src/pages/SearchPage.svelte
<script lang="ts">
import { capitalizeFirstLetter } from '@utils/helpers'
import { Link } from 'svelte-navigator'

export let query: IPokemon[]
export let searchQuery: string
</script>

<ul class="m-2">
  {#if !query.length}
    <p>No results of {searchQuery}</p>
  {/if}

  {#each query as pokemon, i}
    <Link to="{`/pokemon/${pokemon.name}`}">
      <li class="cursor-pointer hover:bg-green-700 p-2 text-sm">
        {i + 1}.{capitalizeFirstLetter(pokemon.name)}
      </li>
    </Link>
  {/each}
</ul>

// react-pokedex/src/pages/SearchPage/SearchPage.tsx
import { Link } from 'react-router-dom'
import { capitalizeFirstLetter } from '@utils/helpers'
import { SearchPageProps } from './SearchPage.types'

const SearchPage = ({ data, searchQuery }: SearchPageProps) => {
  if (!data?.length) {
    return <p className="m-2">No results of {searchQuery}</p>
  }

  return (
    <ul className="m-2">
      {data.map((pokemon) => (
        <Link key={pokemon.name} to={`/pokemon/${pokemon.name}`}>
          <li className="cursor-pointer hover:bg-green-700 p-2">
            {capitalizeFirstLetter(pokemon.name)}
          </li>
        </Link>
      ))}
    </ul>
  )
}

export default SearchPage
